### ISSUE TITLE
Presentation edits

### ISSUE THREAD

**Issue by katyhuff** [arfc/2018-rykhl-bwsymposium#2]
- Aim for fewer slides
- Less jargon (avoid words only a nuclear engineer knows, like "light water reactor")
- More computer facts (number of CPU hours burned, etc.)
- Cite pictures as appropriate (moltres paper, gavin poster)
- Good pictures look good!

Notes here:
[2018-rykhl-bwsymposium.pdf](https://github.com/arfc/2018-rykhl-bwsymposium/files/2013388/2018-rykhl-bwsymposium.pdf)

**Comment by andrewryh** [comment]
I have added scalability study pictures in slides, but they are very boring and I have too many slides already, so, I removed it.
I gonna add text information about nodes-hours burned on existing slides.
